import Head from "next/head";

import { Navigation } from "../../components/navigation";
import { Footer } from "../../components/footer";
import { ProductTable } from "../../components/product-table";
import { CartSummary } from "../../components/cart-summary";

import { inter, spaceGrotesk } from "../../styles/fonts";
import styles from "./cart.module.scss";

export default function MainPage() {
  return (
    <>
      <Head>
        <title>Next-shop</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className={inter.className}>
        <header className={styles.header}>
          <Navigation />
          <div className={styles.header__container}></div>
          <h2
            className={`display-4 text-center ${spaceGrotesk.className} ${styles.header__text}`}
          >
            Cart
          </h2>
        </header>
        <main className="container">
          <section className="products">
            <ProductTable />
          </section>
          <section className="row options">
            <div className="col-md-6"></div>
            <div className="col-md-6">
              <CartSummary />
            </div>
          </section>
        </main>
        <Footer />
      </div>
    </>
  );
}
