import Head from "next/head";

import { Navigation } from "../../components/navigation";
import { Footer } from "../../components/footer";
import { ProductGallery } from "../../components/product-gallery";

import { inter, spaceGrotesk } from "../../styles/fonts";
import styles from "./product.module.scss";

import { product } from "../../store/data";

export default function ProductPage() {
  return (
    <>
      <Head>
        <title>Next-shop</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className={inter.className}>
        <header className={styles.header}>
          <Navigation />
        </header>
        <main className={"container " + styles.main}>
          <div className="row">
            <div className="col-md-6">
              <ProductGallery product={product} />
            </div>
            <div className="col-md-6">product detail</div>
          </div>
          <div className="row">details</div>
        </main>
        <Footer />
      </div>
    </>
  );
}
