import Head from "next/head";

import { Navigation } from "../components/navigation";
import { Slider } from "../components/slider";

import { inter, spaceGrotesk } from "../styles/fonts";

export default function MainPage() {
  return (
    <>
      <Head>
        <title>Next-shop</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className={inter.className}>
        <header>
          <Navigation />
          <Slider />
        </header>
        <main></main>
      </div>
    </>
  );
}
