import Head from "next/head";
import { useState } from "react";

import { Navigation } from "../../../components/navigation";
import { Footer } from "../../../components/footer";
import { ProductGallery } from "../../../components/product-gallery";
import { ProductDetail } from "../../../components/product-detail";
import { DetailTabs } from "../../../components/detail-tabs";
import { ProductSlider } from "../../../components/product-slider";
import { LightboxModal } from "../../../components/lightbox-modal";

import { inter, spaceGrotesk } from "../../../styles/fonts";
import styles from "./product.module.scss";

import { product } from "../../../store/data";
import { useWindowSize } from "../../../hooks/useWindowSize";

export default function ProductPage() {
  const [currentImgIdx, setCurrentImgIdx] = useState(0);

  const { width } = useWindowSize();
  const bpMd = 768;

  return (
    <>
      <Head>
        <title>Next-shop</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className={inter.className}>
        <header className={styles.header}>
          <Navigation />
        </header>
        <main className={"container " + styles.main}>
          <div className="row">
            <div className="col-md-6">
              {width && width < bpMd ? (
                <ProductSlider product={product} />
              ) : (
                <ProductGallery
                  product={product}
                  currentImgIdx={currentImgIdx}
                  setCurrentImgIdx={setCurrentImgIdx}
                />
              )}
            </div>
            <div className="col-md-6">
              <ProductDetail product={product} />
            </div>
          </div>
          <div className="row">
            <DetailTabs />
          </div>
        </main>
        <Footer />
        <LightboxModal
          product={product}
          currentImgIdx={currentImgIdx}
          setCurrentImgIdx={setCurrentImgIdx}
        />
      </div>
    </>
  );
}
