import "./../_styles/globals.css";

import type { Metadata } from "next";
import { Space_Grotesk, Inter } from "next/font/google";
import { notFound } from "next/navigation";

import Header from "../_components/layouts/Header";
import Footer from "../_components/layouts/Footer";
import Toast from "../_components/Toast";

import { AuthProvider } from "../_providers/AuthProvider";
import { TrpcQueryProvider } from "../_providers/TrpcQueryProvider";
import { locales } from "../_i18n";
import { IntlProvider } from "../_providers/IntlProvider";

const spaceGrotesk = Space_Grotesk({
  subsets: ["latin"],
  variable: "--display-font",
});

const inter = Inter({
  subsets: ["latin"],
  variable: "--body-font",
});

export const metadata: Metadata = {
  title: "Next Shop",
  description: "Generated by create next app",
};

interface Props {
  children: React.ReactNode;
  params: { locale: string };
}

export default function RootLayout({ children, params: { locale } }: Props) {
  const isValidLocale = locales.some((cur) => cur === locale);
  if (!isValidLocale) notFound();

  return (
    <html lang={locale}>
      <body
        className={`${spaceGrotesk.variable} ${inter.variable} flex flex-col min-h-screen [&>footer]:mt-auto relative`}
      >
        <TrpcQueryProvider>
          <AuthProvider>
            <IntlProvider locale={locale}>
              <Header />
              <main>{children}</main>
              <Footer />
              <div id="modals" />
              <Toast />
            </IntlProvider>
          </AuthProvider>
        </TrpcQueryProvider>
      </body>
    </html>
  );
}
